// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnnxOjSqMGka0UOGCwlXnWbi54g5lpsQ8',
    appId: '1:271500279198:web:e04648e8e01eea5829aa8f',
    messagingSenderId: '271500279198',
    projectId: 'flutterapp-6a11c',
    authDomain: 'flutterapp-6a11c.firebaseapp.com',
    storageBucket: 'flutterapp-6a11c.appspot.com',
    measurementId: 'G-X4T3CY5LRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1BS8HIeIfUgwwf_Mczzry_HZkRX8YB4',
    appId: '1:271500279198:android:19733306e659371729aa8f',
    messagingSenderId: '271500279198',
    projectId: 'flutterapp-6a11c',
    storageBucket: 'flutterapp-6a11c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY32Gphih9hDGxUD8WJps-thd0hQDi2J0',
    appId: '1:271500279198:ios:c110d12198c2e20e29aa8f',
    messagingSenderId: '271500279198',
    projectId: 'flutterapp-6a11c',
    storageBucket: 'flutterapp-6a11c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY32Gphih9hDGxUD8WJps-thd0hQDi2J0',
    appId: '1:271500279198:ios:c110d12198c2e20e29aa8f',
    messagingSenderId: '271500279198',
    projectId: 'flutterapp-6a11c',
    storageBucket: 'flutterapp-6a11c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnnxOjSqMGka0UOGCwlXnWbi54g5lpsQ8',
    appId: '1:271500279198:web:ff6207299fb6dde429aa8f',
    messagingSenderId: '271500279198',
    projectId: 'flutterapp-6a11c',
    authDomain: 'flutterapp-6a11c.firebaseapp.com',
    storageBucket: 'flutterapp-6a11c.appspot.com',
    measurementId: 'G-PZDWVWYGKQ',
  );
}
